# Compose file for testing traefik-kop itself from within a container env
version: "3"

services:
  traefik-kop:
    image: "ghcr.io/faviann/traefik-kop:0.12.2-next-amd64"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      REDIS_ADDR: "172.28.183.97:6380"
      BIND_IP: "172.28.183.97"
      DEBUG: "1"
      DOCKER_CONFIG: |
        ---
        docker:
          exposedByDefault: false
          useBindPortIP: true
